@php
$bankList = [
    ['code' => '0', 'name' => 'TRANSAKSI_TUNAI'],
    ['code' => '0', 'name' => 'INDONESIA EXIMBANK'],
    ['code' => '0', 'name' => 'POS INDONESIA'],
    ['code' => '2', 'name' => 'BANK RAKYAT INDONESIA'],
    ['code' => '8', 'name' => 'BANK MANDIRI'],
    ['code' => '9', 'name' => 'BANK NEGARA INDONESIA'],
    ['code' => '11', 'name' => 'BANK DANAMON SYARIAH'],
    ['code' => '11', 'name' => 'BANK DANAMON'],
    ['code' => '13', 'name' => 'BANK PERMATA SYARIAH'],
    ['code' => '13', 'name' => 'BANK PERMATA'],
    ['code' => '14', 'name' => 'BANK CENTRAL ASIA'],
    ['code' => '16', 'name' => 'BANK MAYBANK INDONESIA'],
    ['code' => '16', 'name' => 'BANK MAYBANK INDONESIA SYARIAH'],
    ['code' => '19', 'name' => 'BANK PANIN'],
    ['code' => '22', 'name' => 'BANK CIMB NIAGA SYARIAH'],
    ['code' => '22', 'name' => 'BANK CIMB NIAGA'],
    ['code' => '23', 'name' => 'BANK UOB BUANA'],
    ['code' => '28', 'name' => 'BANK OCBC NISP'],
    ['code' => '28', 'name' => 'BANK OCBC NISP SYARIAH'],
    ['code' => '31', 'name' => 'CITIBANK'],
    ['code' => '32', 'name' => 'JPMORGAN CHASE BANK'],
    ['code' => '33', 'name' => 'BANK OF AMERICA'],
    ['code' => '36', 'name' => 'BANK WINDU KENTJANA INTERNATIONAL'],
    ['code' => '37', 'name' => 'BANK ARTHA GRAHA INTERNASIONAL'],
    ['code' => '40', 'name' => 'BANGKOK BANK PUBLIC CO. LTD'],
    ['code' => '41', 'name' => 'HSBC SYARIAH'],
    ['code' => '41', 'name' => 'HSBC'],
    ['code' => '42', 'name' => 'MUFG BANK, LTD'],
    ['code' => '45', 'name' => 'BANK SUMITOMO MITSUI INDONESIA'],
    ['code' => '46', 'name' => 'BANK DBS INDONESIA'],
    ['code' => '47', 'name' => 'BANK RESONA PERDANIA'],
    ['code' => '48', 'name' => 'BANK MIZUHO INDONESIA'],
    ['code' => '50', 'name' => 'STANDARD CHARTERED BANK'],
    ['code' => '52', 'name' => 'THE ROYAL BANK OF SCOTLAND N.V.'],
    ['code' => '54', 'name' => 'BANK CAPITAL INDONESIA'],
    ['code' => '57', 'name' => 'BANK BNP PARIBAS INDONESIA'],
    ['code' => '59', 'name' => 'BANK KEB INDONESIA'],
    ['code' => '60', 'name' => 'PT.BANK RABOBANK INTERNATIONAL INDONESIA'],
    ['code' => '61', 'name' => 'ANZ PANIN BANK'],
    ['code' => '67', 'name' => 'DEUTSCHE BANK AG'],
    ['code' => '68', 'name' => 'BANK WOORI INDONESIA'],
    ['code' => '69', 'name' => 'BANK OF CHINA LIMITED'],
    ['code' => '76', 'name' => 'BANK BUMI ARTA'],
    ['code' => '87', 'name' => 'BANK EKONOMI RAHARJA'],
    ['code' => '88', 'name' => 'BANK ANTARDAERAH'],
    ['code' => '89', 'name' => 'BANK RABOBANK INTERNATIONAL INDONESIA'],
    ['code' => '95', 'name' => 'BANK MUTIARA'],
    ['code' => '97', 'name' => 'BANK MAYAPADA INTERNATIONAL'],
    ['code' => '110', 'name' => 'BPD JABAR BANTEN'],
    ['code' => '111', 'name' => 'BPD DKI SYARIAH'],
    ['code' => '111', 'name' => 'BPD DKI'],
    ['code' => '112', 'name' => 'BPD YOGYAKARTA'],
    ['code' => '112', 'name' => 'BPD YOGYAKARTA SYARIAH'],
    ['code' => '113', 'name' => 'BPD JAWA TENGAH SYARIAH'],
    ['code' => '113', 'name' => 'BPD JAWA TENGAH'],
    ['code' => '114', 'name' => 'BPD JAWA TIMUR SYARIAH'],
    ['code' => '114', 'name' => 'BPD JAWA TIMUR'],
    ['code' => '115', 'name' => 'BPD JAMBI'],
    ['code' => '116', 'name' => 'BPD ACEH SYARIAH'],
    ['code' => '116', 'name' => 'BPD ACEH'],
    ['code' => '117', 'name' => 'BPD SUMATERA UTARA SYARIAH'],
    ['code' => '117', 'name' => 'BPD SUMATERA UTARA'],
    ['code' => '118', 'name' => 'BPD SUMATERA BARAT SYARIAH'],
    ['code' => '118', 'name' => 'BPD SUMATERA BARAT'],
    ['code' => '119', 'name' => 'BPD RIAU'],
    ['code' => '119', 'name' => 'BPD RIAU SYARIAH'],
    ['code' => '120', 'name' => 'BPD SUMSEL dan BABEL'],
    ['code' => '120', 'name' => 'BPD SUMSEL dan BABEL SYARIAH'],
    ['code' => '121', 'name' => 'BPD LAMPUNG'],
    ['code' => '122', 'name' => 'BPD KALIMANTAN SELATAN SYARIAH'],
    ['code' => '122', 'name' => 'BPD KALIMANTAN SELATAN'],
    ['code' => '123', 'name' => 'BPD KALIMANTAN BARAT SYARIAH'],
    ['code' => '123', 'name' => 'BPD KALIMANTAN BARAT'],
    ['code' => '124', 'name' => 'BPD KALIMANTAN TIMUR'],
    ['code' => '124', 'name' => 'BPD KALIMANTAN TIMUR SYARIAH'],
    ['code' => '125', 'name' => 'BPD KALIMANTAN TENGAH'],
    ['code' => '126', 'name' => 'BPD SULAWESI SELATAN'],
    ['code' => '126', 'name' => 'BPD SULAWESI SELATAN SYARIAH'],
    ['code' => '127', 'name' => 'BPD SULAWESI UTARA'],
    ['code' => '128', 'name' => 'BPD NUSA TENGGARA BARAT SYARIAH'],
    ['code' => '128', 'name' => 'BPD NUSA TENGGARA BARAT'],
    ['code' => '129', 'name' => 'BPD BALI'],
    ['code' => '130', 'name' => 'BPD NUSA TENGGARA TIMUR'],
    ['code' => '131', 'name' => 'BPD MALUKU'],
    ['code' => '132', 'name' => 'BPD PAPUA'],
    ['code' => '133', 'name' => 'BPD BENGKULU'],
    ['code' => '134', 'name' => 'BPD SULAWESI TENGAH'],
    ['code' => '135', 'name' => 'BPD SULAWESI TENGGARA'],
    ['code' => '145', 'name' => 'BANK NUSANTARA PARAHYANGAN'],
    ['code' => '146', 'name' => 'BANK SWADESI'],
    ['code' => '147', 'name' => 'BANK MUAMALAT INDONESIA'],
    ['code' => '151', 'name' => 'BANK MESTIKA DHARMA'],
    ['code' => '152', 'name' => 'BANK METRO EXPRESS'],
    ['code' => '153', 'name' => 'BANK SINARMAS'],
    ['code' => '153', 'name' => 'BANK SINARMAS SYARIAH'],
    ['code' => '157', 'name' => 'BANK MASPION INDONESIA'],
    ['code' => '161', 'name' => 'BANK GANESHA'],
    ['code' => '164', 'name' => 'BANK ICBC INDONESIA'],
    ['code' => '167', 'name' => 'BANK KESAWAN'],
    ['code' => '200', 'name' => 'BANK TABUNGAN NEGARA'],
    ['code' => '200', 'name' => 'BANK TABUNGAN NEGARA SYARIAH'],
    ['code' => '212', 'name' => 'BANK HIMPUNAN SAUDARA 1906'],
    ['code' => '213', 'name' => 'BANK TABUNGAN PENSIUNAN NASIONAL SYARIAH'],
    ['code' => '213', 'name' => 'BANK TABUNGAN PENSIUNAN NASIONAL'],
    ['code' => '385', 'name' => 'BANK INDONESIA'],
    ['code' => '405', 'name' => 'BANK VICTORIA SYARIAH'],
    ['code' => '422', 'name' => 'BANK RAKYAT INDONESIA SYARIAH'],
    ['code' => '425', 'name' => 'BPD JABAR BANTEN SYARIAH'],
    ['code' => '426', 'name' => 'BANK MEGA'],
    ['code' => '427', 'name' => 'BANK NEGARA INDONESIA SYARIAH'],
    ['code' => '441', 'name' => 'BANK BUKOPIN'],
    ['code' => '451', 'name' => 'BANK MANDIRI SYARIAH'],
    ['code' => '459', 'name' => 'BANK BISNIS INTERNASIONAL'],
    ['code' => '466', 'name' => 'BANK ANDARA'],
    ['code' => '472', 'name' => 'BANK JASA JAKARTA'],
    ['code' => '484', 'name' => 'BANK HANA'],
    ['code' => '485', 'name' => 'BANK ICB BUMIPUTERA'],
    ['code' => '490', 'name' => 'BANK YUDHA BHAKTI'],
    ['code' => '491', 'name' => 'BANK MITRA NIAGA'],
    ['code' => '494', 'name' => 'BANK AGRONIAGA'],
    ['code' => '498', 'name' => 'BANK SBI INDONESIA'],
    ['code' => '501', 'name' => 'BANK ROYAL INDONESIA'],
    ['code' => '503', 'name' => 'BANK NATIONAL NOBU'],
    ['code' => '506', 'name' => 'BANK MEGA SYARIAH'],
    ['code' => '513', 'name' => 'BANK INA PERDANA'],
    ['code' => '517', 'name' => 'BANK PANIN SYARIAH'],
    ['code' => '520', 'name' => 'PRIMA MASTER BANK'],
    ['code' => '521', 'name' => 'BANK BUKOPIN SYARIAH'],
    ['code' => '523', 'name' => 'DIPO INTERNASIONAL BANK'],
    ['code' => '525', 'name' => 'BANK BARCLAYS INDONESIA'],
    ['code' => '526', 'name' => 'LIMAN INTERNASIONAL BANK'],
    ['code' => '531', 'name' => 'ANGLOMAS INTERNATIONAL BANK'],
    ['code' => '535', 'name' => 'BANK KESEJAHTERAAN EKONOMI'],
    ['code' => '536', 'name' => 'BANK CENTRAL ASIA SYARIAH'],
    ['code' => '542', 'name' => 'BANK ARTOS INDONESIA'],
    ['code' => '547', 'name' => 'BANK SAHABAT PURBA DANARTA'],
    ['code' => '548', 'name' => 'BANK MULTI ARTA SENTOSA'],
    ['code' => '553', 'name' => 'BANK MAYORA'],
    ['code' => '555', 'name' => 'BANK INDEX SELINDO'],
    ['code' => '558', 'name' => 'BANK PUNDI INDONESIA'],
    ['code' => '559', 'name' => 'CENTRATAMA NASIONAL BANK'],
    ['code' => '562', 'name' => 'BANK FAMA INTERNATIONAL'],
    ['code' => '564', 'name' => 'BANK SINAR HARAPAN BALI'],
    ['code' => '566', 'name' => 'BANK VICTORIA INTERNATIONAL'],
    ['code' => '567', 'name' => 'BANK HARDA INTERNASIONAL'],
    ['code' => '945', 'name' => 'BANK AGRIS'],
    ['code' => '947', 'name' => 'BANK MAYBANK SYARIAH'],
    ['code' => '949', 'name' => 'BANK CHINATRUST INDONESIA'],
    ['code' => '950', 'name' => 'BANK COMMONWEALTH'],
];
@endphp

@foreach($bankList as $bank)
    @php
        $isSelected = false;
        if (isset($selectedName) && $selectedName != '') {
            if ($selectedName == $bank['name'] && ($selected ?? '') == $bank['code']) {
                $isSelected = true;
            }
        } elseif (isset($selected) && $selected != '' && $selected == $bank['code']) {
            $isSelected = true;
        }
    @endphp
    <option value="{{ $bank['code'] }}" data-name="{{ $bank['name'] }}" {{ $isSelected ? 'selected' : '' }}>
        {{ $bank['code'] }} - {{ $bank['name'] }}
    </option>
@endforeach
